import { SCREEN_CONTENT_WIDTH } from '../../styles/constants'

export const DRAWING_ITEM_MARGIN = 20
export const DRAWINGS_COLUMNS_COUNT = 2

export const DRAWING_ITEM_WIDTH =
  SCREEN_CONTENT_WIDTH / DRAWINGS_COLUMNS_COUNT + DRAWING_ITEM_MARGIN / 2

export const DRAWING_ITEM_HEIGHT = DRAWING_ITEM_WIDTH
