export enum links {
  /** auth */
  signUp = 'signUp',
  phoneEnter = 'phoneEnter',
  verification = 'verification',
  login = 'login',
  passwordEnter = 'passwordEnter',
  passwordRecover = 'passwordRecover',
  /** main */
  home = 'home',
  homeMain = 'homeMain',
  competitionCategory = 'competitionCategory',
  /** gallery */
  gallery = 'gallery',
  galleryMain = 'galleryMain',
  galleryFilter = 'galleryFilter',
  /** post */
  createPost = 'createPost',
  uploadPostImage = 'uploadPostImage',
  addPostDescription = 'addPostDescription',
  postCard = 'postCard',
  /** profile */
  profile = 'profile',
  profileMain = 'profileMain',
  editProfile = 'editProfile',
  /** settings */
  settings = 'settings',
  settingsMain = 'settingsMain',
  faq = 'faq',
  feedback = 'feedback',
  language = 'language',
  notifications = 'notifications',
  deleteAccount = 'deleteAccount',
  /** subscription */
  subscriptionOptions = 'subscriptionOptions',
  userSubscription = 'userSubscription',
  addPaymentCard = 'addPaymentCard',
  paymentMethod = 'paymentMethod',
}
